import {
  DatasetSpec,
  QualityResponse,
} from '../types';


export const FIXTURE_CHURN_SPEC: DatasetSpec = {
  name: 'customer_churn',
  version: '1.0',
  locale: 'en_US',
  seed: 42,
  tables: [
    {
      name: 'customer_churn',
      row_count: 200,
      primary_key: 'customer_id',
      correlation_columns: [
        'tenure_months',
        'monthly_charges',
        'total_charges',
      ],
      correlation_matrix: [
        [1.0, 0.24, 0.82],
        [0.24, 1.0, 0.65],
        [0.82, 0.65, 1.0],
      ],
      columns: [
        {
          name: 'customer_id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, min: 1001, max: 1200 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'gender',
          dtype: 'string',
          semantic_type: 'categorical',
          nullable: false,
          null_rate: 0,
          constraints: { categories: ['Female', 'Male'] },
          distribution: {
            type: 'categorical',
            values: ['Female', 'Male'],
            probabilities: [0.5, 0.5],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'senior_citizen',
          dtype: 'integer',
          semantic_type: 'categorical',
          nullable: false,
          null_rate: 0,
          constraints: { categories: [0, 1] },
          distribution: {
            type: 'categorical',
            values: [0, 1],
            probabilities: [0.85, 0.15],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'tenure_months',
          dtype: 'integer',
          semantic_type: 'numeric',
          nullable: false,
          null_rate: 0,
          constraints: { min: 1, max: 72 },
          distribution: {
            type: 'gaussian',
            mean: 32.4,
            std: 24.1,
          },
          outlier_rate: 0.01,
          outlier_scale: 5,
        },
        {
          name: 'monthly_charges',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 18.2, max: 118.7 },
          distribution: {
            type: 'gaussian',
            mean: 64.9,
            std: 29.8,
          },
          outlier_rate: 0.01,
          outlier_scale: 5,
        },
        {
          name: 'total_charges',
          dtype: 'float',
          semantic_type: 'money',
          nullable: true,
          null_rate: 0.02,
          constraints: { min: 18.2, max: 8684.0 },
          distribution: {
            type: 'gaussian',
            mean: 2283.3,
            std: 2266.7,
          },
          outlier_rate: 0.01,
          outlier_scale: 5,
        },
        {
          name: 'contract_type',
          dtype: 'string',
          semantic_type: 'categorical',
          nullable: false,
          null_rate: 0,
          constraints: {
            categories: ['Month-to-month', 'One year', 'Two year'],
          },
          distribution: {
            type: 'categorical',
            values: ['Month-to-month', 'One year', 'Two year'],
            probabilities: [0.55, 0.25, 0.2],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'payment_method',
          dtype: 'string',
          semantic_type: 'categorical',
          nullable: false,
          null_rate: 0,
          constraints: {
            categories: [
              'Electronic check',
              'Mailed check',
              'Bank transfer',
              'Credit card',
            ],
          },
          distribution: {
            type: 'categorical',
            values: [
              'Electronic check',
              'Mailed check',
              'Bank transfer',
              'Credit card',
            ],
            probabilities: [0.35, 0.25, 0.2, 0.2],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'churn',
          dtype: 'string',
          semantic_type: 'categorical',
          nullable: false,
          null_rate: 0,
          constraints: { categories: ['No', 'Yes'] },
          distribution: {
            type: 'categorical',
            values: ['No', 'Yes'],
            probabilities: [0.73, 0.27],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
    },
  ],
};

export const FIXTURE_CHURN_PREVIEW: Record<string, any>[] = [
  {
    customer_id: 1001,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 3,
    monthly_charges: 39.7,
    total_charges: 113.1,
    contract_type: 'Month-to-month',
    payment_method: 'Electronic check',
    churn: 'Yes',
  },
  {
    customer_id: 1002,
    gender: 'Male',
    senior_citizen: 0,
    tenure_months: 6,
    monthly_charges: 44.4,
    total_charges: 253.1,
    contract_type: 'One year',
    payment_method: 'Mailed check',
    churn: 'No',
  },
  {
    customer_id: 1003,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 9,
    monthly_charges: 49.1,
    total_charges: 419.8,
    contract_type: 'Two year',
    payment_method: 'Bank transfer',
    churn: 'No',
  },
  {
    customer_id: 1004,
    gender: 'Male',
    senior_citizen: 0,
    tenure_months: 12,
    monthly_charges: 53.8,
    total_charges: 613.3,
    contract_type: 'Month-to-month',
    payment_method: 'Credit card',
    churn: 'No',
  },
  {
    customer_id: 1005,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 15,
    monthly_charges: 58.5,
    total_charges: 833.6,
    contract_type: 'One year',
    payment_method: 'Electronic check',
    churn: 'No',
  },
  {
    customer_id: 1006,
    gender: 'Male',
    senior_citizen: 0,
    tenure_months: 18,
    monthly_charges: 63.2,
    total_charges: 1080.7,
    contract_type: 'Two year',
    payment_method: 'Mailed check',
    churn: 'No',
  },
  {
    customer_id: 1007,
    gender: 'Female',
    senior_citizen: 1,
    tenure_months: 21,
    monthly_charges: 67.9,
    total_charges: 1354.6,
    contract_type: 'Month-to-month',
    payment_method: 'Bank transfer',
    churn: 'No',
  },
  {
    customer_id: 1008,
    gender: 'Male',
    senior_citizen: 0,
    tenure_months: 24,
    monthly_charges: 72.6,
    total_charges: 1655.3,
    contract_type: 'One year',
    payment_method: 'Credit card',
    churn: 'No',
  },
  {
    customer_id: 1009,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 27,
    monthly_charges: 77.3,
    total_charges: 1982.7,
    contract_type: 'Two year',
    payment_method: 'Electronic check',
    churn: 'Yes',
  },
  {
    customer_id: 1010,
    gender: 'Male',
    senior_citizen: 0,
    tenure_months: 30,
    monthly_charges: 82.0,
    total_charges: 2337.0,
    contract_type: 'Month-to-month',
    payment_method: 'Mailed check',
    churn: 'Yes',
  },
  {
    customer_id: 1011,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 33,
    monthly_charges: 86.7,
    total_charges: 2718.1,
    contract_type: 'One year',
    payment_method: 'Bank transfer',
    churn: 'No',
  },
  {
    customer_id: 1012,
    gender: 'Male',
    senior_citizen: 0,
    tenure_months: 36,
    monthly_charges: 91.4,
    total_charges: 3125.9,
    contract_type: 'Two year',
    payment_method: 'Credit card',
    churn: 'No',
  },
  {
    customer_id: 1013,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 39,
    monthly_charges: 96.1,
    total_charges: 3560.5,
    contract_type: 'Month-to-month',
    payment_method: 'Electronic check',
    churn: 'Yes',
  },
  {
    customer_id: 1014,
    gender: 'Male',
    senior_citizen: 1,
    tenure_months: 42,
    monthly_charges: 100.8,
    total_charges: 4021.9,
    contract_type: 'One year',
    payment_method: 'Mailed check',
    churn: 'No',
  },
  {
    customer_id: 1015,
    gender: 'Female',
    senior_citizen: 0,
    tenure_months: 45,
    monthly_charges: 105.5,
    total_charges: 4510.1,
    contract_type: 'Two year',
    payment_method: 'Bank transfer',
    churn: 'No',
  },
];

export const FIXTURE_CHURN_QUALITY: QualityResponse = {
  overall_score: 93.8,
  score_status: 'available',
  distribution_columns_evaluated: 9,
  distribution_columns_total: 9,
  components: {
    distribution: 0.942,
    missingness: 0.985,
    correlation: 0.887,
  },
  reference_rows: 200,
  synthetic_rows: 200,
  score_definition:
    '100 * mean(available components). Distribution = mean(1-KS numeric, 1-TVD categorical); missingness = mean(1-absolute null-rate difference); correlation = 1-mean absolute Pearson pair difference/2.',
  correlation: {
    columns: ['tenure_months', 'monthly_charges', 'total_charges'],
    similarity: 0.887,
    frobenius_distance: 0.226,
    pair_count: 3,
    real_matrix: [
      [1.0, 0.24, 0.82],
      [0.24, 1.0, 0.65],
      [0.82, 0.65, 1.0],
    ],
    synthetic_matrix: [
      [1.0, 0.21, 0.79],
      [0.21, 1.0, 0.62],
      [0.79, 0.62, 1.0],
    ],
  },
  columns: [
    {
      name: 'monthly_charges',
      kind: 'numeric',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.954,
      ks_statistic: 0.046,
      wasserstein_distance: 2.15,
      histogram: {
        edges: [18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 118],
        real: [0.06, 0.08, 0.09, 0.11, 0.13, 0.14, 0.12, 0.1, 0.08, 0.05, 0.04],
        synthetic: [
          0.05, 0.09, 0.1, 0.1, 0.14, 0.13, 0.13, 0.09, 0.08, 0.05, 0.04,
        ],
      },
    },
    {
      name: 'tenure_months',
      kind: 'numeric',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.962,
      ks_statistic: 0.038,
      wasserstein_distance: 1.45,
      histogram: {
        edges: [1, 7, 14, 21, 28, 35, 42, 49, 56, 63, 72],
        real: [0.15, 0.12, 0.1, 0.09, 0.08, 0.08, 0.09, 0.09, 0.1, 0.1],
        synthetic: [0.14, 0.13, 0.09, 0.1, 0.08, 0.08, 0.09, 0.1, 0.09, 0.1],
      },
    },
    {
      name: 'total_charges',
      kind: 'numeric',
      real_null_rate: 0.02,
      synthetic_null_rate: 0.015,
      missing_similarity: 0.995,
      distribution_similarity: 0.931,
      ks_statistic: 0.069,
      wasserstein_distance: 98.4,
      histogram: {
        edges: [18, 800, 1600, 2400, 3200, 4000, 4800, 5600, 6400, 7200, 8684],
        real: [0.28, 0.18, 0.14, 0.11, 0.09, 0.07, 0.05, 0.04, 0.02, 0.02],
        synthetic: [
          0.26, 0.19, 0.15, 0.11, 0.08, 0.07, 0.06, 0.04, 0.02, 0.02,
        ],
      },
    },
    {
      name: 'contract_type',
      kind: 'categorical',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.975,
      total_variation_distance: 0.025,
      categories: [
        { value: 'Month-to-month', real: 0.55, synthetic: 0.535 },
        { value: 'One year', real: 0.25, synthetic: 0.26 },
        { value: 'Two year', real: 0.2, synthetic: 0.205 },
      ],
    },
    {
      name: 'payment_method',
      kind: 'categorical',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.96,
      total_variation_distance: 0.04,
      categories: [
        { value: 'Electronic check', real: 0.35, synthetic: 0.34 },
        { value: 'Mailed check', real: 0.25, synthetic: 0.26 },
        { value: 'Bank transfer', real: 0.2, synthetic: 0.19 },
        { value: 'Credit card', real: 0.2, synthetic: 0.21 },
      ],
    },
    {
      name: 'gender',
      kind: 'categorical',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.98,
      total_variation_distance: 0.02,
      categories: [
        { value: 'Female', real: 0.5, synthetic: 0.49 },
        { value: 'Male', real: 0.5, synthetic: 0.51 },
      ],
    },
    {
      name: 'churn',
      kind: 'categorical',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.965,
      total_variation_distance: 0.035,
      categories: [
        { value: 'No', real: 0.73, synthetic: 0.715 },
        { value: 'Yes', real: 0.27, synthetic: 0.285 },
      ],
    },
    {
      name: 'senior_citizen',
      kind: 'categorical',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.985,
      total_variation_distance: 0.015,
      categories: [
        { value: '0', real: 0.85, synthetic: 0.845 },
        { value: '1', real: 0.15, synthetic: 0.155 },
      ],
    },
    {
      name: 'customer_id',
      kind: 'categorical',
      real_null_rate: 0,
      synthetic_null_rate: 0,
      missing_similarity: 1.0,
      distribution_similarity: 0.92,
      total_variation_distance: 0.08,
      categories: [],
      reason: 'Unique identifier column',
    },
  ],
};

import commerceExample from './v2-example.json';
export const FIXTURE_COMMERCE_SPEC: DatasetSpec = commerceExample as unknown as DatasetSpec;

