import { DatasetSpec } from '../types';

export const COMMERCE_RELATIONAL_SPEC: DatasetSpec = {
  name: 'E-Commerce & Invoices',
  version: '2.0',
  locale: 'en_US',
  seed: 22,
  tables: [
    {
      name: 'Customers',
      row_count: 10,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'name',
          dtype: 'string',
          semantic_type: 'person_name',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'email',
          dtype: 'string',
          semantic_type: 'email',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'address',
          dtype: 'string',
          semantic_type: 'address',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [],
    },
    {
      name: 'Products',
      row_count: 8,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'product_name',
          dtype: 'string',
          semantic_type: 'generic_text',
          nullable: false,
          null_rate: 0,
          constraints: {
            categories: [
              'Wireless Headphones',
              'Mechanical Keyboard',
              '4K Monitor',
              'Ergonomic Mouse',
              'USB-C Dock',
              'Desk Lamp',
              'Webcam Pro',
              'Laptop Stand',
            ],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'unit_price',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 25, max: 350 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [],
    },
    {
      name: 'Orders',
      row_count: 25,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'customer_id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'order_date',
          dtype: 'datetime',
          semantic_type: 'datetime',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'total',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 10, max: 2000 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [
        {
          column: 'customer_id',
          reference_table: 'Customers',
          reference_column: 'id',
          cardinality: '1:N',
          min_children: 1,
        },
      ],
    },
    {
      name: 'OrderItems',
      row_count: 60,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'order_id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'product_id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'quantity',
          dtype: 'integer',
          semantic_type: 'numeric',
          nullable: false,
          null_rate: 0,
          constraints: { min: 1, max: 4 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'price',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 20, max: 350 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [
        {
          column: 'order_id',
          reference_table: 'Orders',
          reference_column: 'id',
          cardinality: '1:N',
          min_children: 1,
        },
        {
          column: 'product_id',
          reference_table: 'Products',
          reference_column: 'id',
          cardinality: '1:N',
        },
      ],
    },
    {
      name: 'Payments',
      row_count: 25,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'order_id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'method',
          dtype: 'string',
          semantic_type: 'generic_text',
          nullable: false,
          null_rate: 0,
          constraints: {
            categories: ['Credit Card', 'Bank Transfer', 'PayPal', 'Apple Pay'],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'status',
          dtype: 'string',
          semantic_type: 'generic_text',
          nullable: false,
          null_rate: 0,
          constraints: { categories: ['Paid', 'Settled'] },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [
        {
          column: 'order_id',
          reference_table: 'Orders',
          reference_column: 'id',
          cardinality: '1:1',
          min_children: 1,
        },
      ],
    },
  ],
  reconciliations: [
    {
      parent_table: 'Orders',
      parent_column: 'total',
      child_table: 'OrderItems',
      foreign_key: 'order_id',
      factors: ['quantity', 'price'],
    },
  ],
  documents: [
    {
      kind: 'invoice',
      parent_table: 'Orders',
      child_table: 'OrderItems',
      foreign_key: 'order_id',
      quantity_column: 'quantity',
      price_column: 'price',
      tax_rate: 0.17,
      discount_rate: 0.0,
    },
  ],
};

export const BANKING_RELATIONAL_SPEC: DatasetSpec = {
  name: 'Retail Banking & Statements',
  version: '2.0',
  locale: 'en_US',
  seed: 42,
  tables: [
    {
      name: 'Accounts',
      row_count: 10,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'account_number',
          dtype: 'string',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'holder_name',
          dtype: 'string',
          semantic_type: 'person_name',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'account_type',
          dtype: 'string',
          semantic_type: 'generic_text',
          nullable: false,
          null_rate: 0,
          constraints: { categories: ['Checking', 'Savings', 'Premium'] },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'opening_balance',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 1000, max: 10000 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [],
    },
    {
      name: 'Transactions',
      row_count: 50,
      primary_key: 'id',
      columns: [
        {
          name: 'id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: { unique: true, auto_increment: true },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'account_id',
          dtype: 'integer',
          semantic_type: 'id',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'date',
          dtype: 'datetime',
          semantic_type: 'datetime',
          nullable: false,
          null_rate: 0,
          constraints: {},
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'description',
          dtype: 'string',
          semantic_type: 'generic_text',
          nullable: false,
          null_rate: 0,
          constraints: {
            categories: [
              'Payroll Direct Deposit',
              'Supermarket Grocery',
              'Online Subscription',
              'Utility Bill Electric',
              'Mobile Recharge',
              'Restaurant Dining',
              'ATM Cash Withdrawal',
            ],
          },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'credit',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 0, max: 1200 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
        {
          name: 'debit',
          dtype: 'float',
          semantic_type: 'money',
          nullable: false,
          null_rate: 0,
          constraints: { min: 0, max: 800 },
          outlier_rate: 0,
          outlier_scale: 5,
        },
      ],
      foreign_keys: [
        {
          column: 'account_id',
          reference_table: 'Accounts',
          reference_column: 'id',
          cardinality: '1:N',
          min_children: 1,
        },
      ],
    },
  ],
  documents: [
    {
      kind: 'bank_statement',
      parent_table: 'Accounts',
      child_table: 'Transactions',
      foreign_key: 'account_id',
      opening_balance_column: 'opening_balance',
      date_column: 'date',
      credit_column: 'credit',
      debit_column: 'debit',
    },
  ],
};
